public enum EventDefine
{
    ShowRegisterPanel,
    ShowLoginPanel,
    Hint,
    ShowRankListPanel,
    SendRankListDto,
    ShowRechargePanel,
    UpdateCoinCount,
    ShowRoomChoosePanel,
    //VSAI,
    //VSWithSelf,
    //GameOver,

    //联网部分
    //RefreshUI,
    //StartGame,
    //LeftDealCard,
    //RightDealCard,
    //SelfDealCard,
    //LeftBanker,
    //RightBanker,
    //SelfBanker,
    //LeaveFightRoom,
    //StartStakes,
    //LookCardBRO,
    //PutStakesBRO,
    //GiveUpCardBRO,
    //CompareCardBRO,
    //GameOverBRO,
    //ChatBRO,

    //Game Manager
    Player2,
    Player3,
    Player4,
    SciSelected,
    CardShowing,
    CardEndShowing,
    CardActing,
    StopCardActing,
    PatentShowing,
    PatentEndShowing,
    InitHandCard,

    //Acting
    CardDiscard,
    CardDiscardFinish,
    DrawCard0,
    DrawCard1,
    DrawCard2,
    DrawCard3,
    DrawCardFinish,
    Card2Patent,
    Acted,
    MaintenanceFinish,
    DiscardFinish,
    CardShow,
    CardShowFinish,

    //Game Round
    GameStart,
    RoundStart,
    BeforeRound,
    BeforeAction,
    AfterAction,
    BeforeDraw,
    BeforeDiscard,
    AfterDiscard,
    BeforeMaintenance,
    RoundEnd,

}
